apps/blog/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
	url(r'^(?P<subcategory_slug>[\w-]+)/topic/(?P<id>\d+)/$', views.topic, name='topic'),
	url(r'^add-topic/(?P<slug>[\w-]+)/$', views.add_topic, name='add_topic'),
	url(r'^edit-topic/(?P<id>\d+)/$', views.edit_topic, name='edit_topic'),
	url(r'^delete-topic/(?P<id>\d+)/$', views.del_topic, name='del_topic'),


	url(r'^moderated-topic/(?P<id>\d+)/$', views.moderated, name='moderated'),


	url(r'^posts/(?P<id>\d+)/$', views.posts, name='posts'),
	url(r'^add-post/(?P<id>\d+)/$', views.add_post, name='add_post'),
	url(r'^edit-post/(?P<id>\d+)/$', views.edit_post, name='edit_post'),
	url(r'^del-post/(?P<id>\d+)/$', views.del_post, name='del_post'),


	url(r'^good-vote/(?P<id>\d+)/$', views.good_vote, name='good_vote'),
	url(r'^bad-vote/(?P<id>\d+)/$', views.bad_vote, name='bad_vote'),


	url(r'^personal-message/(?P<id>\d+)/$', views.personal_message, name='personal_message'),
	url(r'^send-message/(?P<id>\d+)/$', views.send_message, name='send_message'),
	url(r'^delete-message/(?P<id>\d+)/$', views.del_message, name='del_message'),
	url(r'^del-recipient-message/(?P<id>\d+)/$', views.del_recipient_message, name='del_recipient_message'),


	url(r'^tag/(?P<id>\d+)/$', views.tag, name='tag'),


	url(r'^all-language/$', views.all_language, name='all_language'),
	url(r'^(?P<slug>[\w-]+)/$', views.language, name='language'),
	url(r'^(?P<category_slug>[\w-]+)/(?P<subcategory_slug>[\w-]+)/$', views.subcategory, name='subcategory'),


]

apps/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from . import views


admin.autodiscover()

urlpatterns = patterns('',
	# Home
	url(r'^$', views.home, name='home'),

	# Admin
	url(r'^admin/', include(admin.site.urls)),

	#Search
	url(r'^search/$', views.search, name='search'),

	# Panel
	url(r'^', include('apps.panel.urls')),

	#Accounts
	url(r'^', include('apps.accounts.urls')),

	url(r'^', include('apps.chat.urls')),

	#Blog
	url(r'^', include('apps.blog.urls')),

	# Api
	url(r'^', include('apps.api.urls')),
)

# For serve static, media, templates in develop mode
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static('/templates/', document_root=settings.PROJECT_DIR + '/templates/')

apps/blog/models.py
# coding: utf-8
from django.db.models import Count, Avg
from django.db.models import F
from django.db import models

from ..accounts.models import User


class Category(models.Model):
	title = models.CharField(verbose_name=u'Название', max_length=256)
	short_description = models.TextField(verbose_name=u'Описание')
	slug = models.SlugField(verbose_name=u'Ярлык')

	def __unicode__(self):
		return self.title

	@models.permalink
	def get_absolute_url(self):
		return ('language', (), {'slug': self.slug})

	class Meta:
		verbose_name=u'Категория'
		verbose_name_plural=u'Категории'


class Subcategory(models.Model):
	category = models.ForeignKey(Category, verbose_name=u'Язык', related_name='subcategories')
	title = models.CharField(verbose_name=u'Название', max_length=256)
	slug = models.SlugField(verbose_name=u'Ярлык')

	def __unicode__(self):
		return self.title

	def topic_count(self):
		return self.topics_subcategory.count()

	def topic_posts_count(self):
		posts = {}
		topics = self.topics_subcategory.values('posts').annotate(dcount=Count('posts'))
		return topics.count()

	def topic_last_post(self):
		posts = {}
		topics = Topic.objects.filter(subcategory=self.id)
		for topic in topics:
			post_items = Post.objects.filter(topic=topic, public=False).order_by('-created_at')[:1]
			print post_items
			for post in post_items:
				posts['post'] = {
					'user': post.user,
					'avatar': post.user.avatar,
					'title': post.message,
					'created_at': post.created_at,
				}
		return posts

	class Meta:
		verbose_name=u'Подкатегория'
		verbose_name_plural=u'Подкатегории'


class Tag(models.Model):
	word = models.CharField(max_length=35)
	slug = models.CharField(max_length=250)

	def __unicode__(self):
		return self.word

	@models.permalink
	def get_absolute_url(self):
		return ('tag', (), {'id': self.id})


class Topic(models.Model):
	user = models.ForeignKey(User, verbose_name=u'Юзер', related_name='topics_user')
	subcategory = models.ForeignKey(Subcategory, verbose_name=u'Подкатегория', related_name='topics_subcategory')
	title = models.CharField(verbose_name=u'Название', max_length=256)
	tags = models.ManyToManyField(Tag, verbose_name=u'Тэги', related_name='topic_tags')
	description = models.TextField(verbose_name=u'Описание')
	created_at = models.DateTimeField(verbose_name=u'Дата создания', auto_now_add=True)
	public = models.BooleanField(verbose_name=u'Публикация', default=True)
	moderated = models.BooleanField(verbose_name=u'На проверке модером', default=False)
	count_post = models.PositiveIntegerField(verbose_name=u'Постов', blank=True, null=True)
	count_views = models.PositiveIntegerField(verbose_name=u'Просмотров', default=1)

	def __unicode__(self):
		return self.title

	@models.permalink
	def get_absolute_url(self):
		return ('topic', (), {'slug': self.subcategory.slug, 'id': self.id})

	@models.permalink
	def positive_vote(self):
		return ('good_vote', (), {'id': self.id})

	@models.permalink
	def negative_vote(self):
		return ('bad_vote', (), {'id': self.id})

	def good_vote(self):
		return self.votes.filter(good_vote=True).count()

	def bad_vote(self):
		return self.votes.filter(bad_vote=True).count()

	def posts_count(self):
		posts_with_counts = self.topics_subcategory.filter(public=True).annotate(issue_count=Count('posts'))
		return posts_with_counts

	def last_post(self):
		posts = {}
		post_items = self.posts.filter(public=False).order_by('-created_at')[:1]
		for post in post_items:
			posts['post'] = {
				'user': post.user,
				'avatar': post.user.avatar,
				'created_at': post.created_at,
			}
		return posts


	class Meta:
		verbose_name=u'Топик'
		verbose_name_plural=u'Топики'


class Moderated(models.Model):
	topic = models.ForeignKey(Topic, verbose_name=u'Топик', related_name='topic_moderated')
	user = models.ForeignKey(User, verbose_name=u'Юзер', related_name='moderated_user')
	text = models.CharField(verbose_name=u'Проблема', max_length=256)
	created_at = models.DateTimeField(verbose_name=u'Дата создания', auto_now_add=True)
	moderated = models.BooleanField(verbose_name=u'Проверил модератор', default=False)


class Post(models.Model):
	user = models.ForeignKey(User, verbose_name=u'Юзер', related_name='posts_user')
	topic = models.ForeignKey(Topic, verbose_name=u'Топик', related_name='posts')
	message = models.TextField(verbose_name=u'Пост')
	created_at = models.DateTimeField(verbose_name=u'Дата создания', auto_now_add=True)
	public = models.BooleanField(verbose_name=u'Публикация', default=False)

	def __unicode__(self):
		return self.message

	@models.permalink
	def edit_post(self):
		return ('edit_post', (), {'id': self.id})

	@models.permalink
	def delete_post(self):
		return ('del_post', (), {'id': self.id})


class Vote(models.Model):
	user = models.ForeignKey(User, verbose_name=u'Юзер', related_name='votes_user')
	topic = models.ForeignKey(Topic, verbose_name=u'Топик', related_name='votes')
	good_vote = models.DecimalField(verbose_name=u'Хороший голос', max_digits=6, decimal_places=0, blank=True, null=True)
	bad_vote = models.DecimalField(verbose_name=u'Плохой голос', max_digits=6, decimal_places=0, blank=True, null=True)
	created_at = models.DateTimeField(verbose_name=u'Дата создания', auto_now_add=True)


class TopicMessage(models.Model):
	user = models.ForeignKey(User, verbose_name=u'Юзер', related_name='personalmessage_user', on_delete=models.SET_NULL, null=True)
	recipient = models.ForeignKey(User, verbose_name=u'Юзер получатель', related_name='recipient', blank=True, null=True, on_delete=models.SET_NULL)
	parent = models.ForeignKey('self', verbose_name=u'Родитель', related_name='childs', blank=True, null=True, on_delete=models.SET_NULL)
	topic = models.ForeignKey(Topic, verbose_name=u'Топик', related_name='personalmessage_votes', blank=True, null=True)
	theme = models.CharField(verbose_name=u'', max_length=500)
	message = models.TextField(verbose_name=u'Сообщение')
	delete = models.BooleanField(verbose_name=u'Удаление юзер', default=False)
	delete_recipient = models.BooleanField(verbose_name=u'Удаление получатель', default=False)
	created_at = models.DateTimeField(verbose_name=u'Дата создания', auto_now_add=True)

	def __unicode__(self):
		return self.theme

	class Meta:
		verbose_name='Сообщение'
		verbose_name_plural=u'Сообщения'

apps/blog/forms.py
from django import forms

from ..accounts.models import User

from .models import Topic, Post, TopicMessage, Moderated, Tag


class TopicForm(forms.ModelForm):
	tags = forms.ModelMultipleChoiceField(queryset=Tag.objects.all())
	class Meta:
		model = Topic
		fields = ['title', 'description', 'tags']


class PostForm(forms.ModelForm):
	class Meta:
		model = Post
		fields = ['message']


class ModeratedForm(forms.ModelForm):
	class Meta:
		model = Moderated
		fields = ['text']

class PersonalMessageForm(forms.ModelForm):
	class Meta:
		model = TopicMessage
		fields = ['message']

apps/blog/views.py
# coding: utf-8
import json
from django.shortcuts import render, redirect
from django.db.models import F
from django.http import HttpResponse

from django.db.models import Sum
from django.db.models import Avg

from django.contrib.auth.decorators import login_required

from .models import Category, Subcategory, Topic, Post, Vote, TopicMessage, Tag

from .forms import TopicForm, PostForm, PersonalMessageForm, ModeratedForm


def all_language(request):
	context = {}
	context['title'] = u'Все языки'
	context['languages'] = Category.objects.all()
	return render(request, 'blog/languages.html', context)


def language(request, slug):
	context = {}
	context['title'] = Category.objects.get(slug=slug)
	context['language'] = Category.objects.get(slug=slug)
	return render(request, 'blog/language.html', context)


def subcategory(request, category_slug, subcategory_slug):
	context = {}
	context['title'] = Subcategory.objects.get(slug=subcategory_slug)
	context['subcategory'] = Subcategory.objects.get(category__slug=category_slug, slug=subcategory_slug)
	context['topics'] = Topic.objects.filter(subcategory=context['subcategory'], public=True)
	return render(request, 'blog/subcategory.html', context)


def topic(request, subcategory_slug, id):
	context = {}
	context['title'] = u'Все топики'
	topic = Topic.objects.get(subcategory__slug=subcategory_slug, id=id, public=True)
	topic.count_views += 1
	context['good_vote'] = Vote.objects.filter(topic=topic, good_vote=True).count()
	context['bad_vote'] = Vote.objects.filter(topic=topic, bad_vote=True).count()
	context['posts'] = Post.objects.filter(topic=topic).order_by('-created_at')
	context['post_form'] = PostForm()
	context['count_view'] = Topic.objects.filter(id=topic.id).update(count_views=F('count_views') + 1)
	topic.save()
	context['topic'] = topic
	return render(request, 'topic/topic.html', context)


@login_required
def add_topic(request, slug):
	context = {}
	context['title'] = u'Создать топик'
	subcategory = Subcategory.objects.get(slug=slug)
	context['form'] = TopicForm(request.POST or None, request.FILES or None)
	if context['form'].is_valid():
		new_topic = context['form'].save(commit=False)
		new_topic.user = request.user
		new_topic.subcategory = subcategory
		new_topic.save()
		return redirect('subcategory', subcategory.category.slug, subcategory.slug )
	return render(request, 'topic/add-topic.html', context)


@login_required
def edit_topic(request, id):
	context = {}
	context['title'] = u'Редактирование топика'
	instance = Topic.objects.get(user=request.user, id=id)
	context['form'] = TopicForm(request.POST or None, request.FILES or None, instance=instance)
	if instance.user == request.user:
		if context['form'].is_valid():
			context['form'].save()
			return redirect('subcategory', instance.subcategory.category.slug, instance.subcategory.slug )
	return render(request, 'topic/add-topic.html', context)


@login_required
def del_topic(request, id):
	context = {}
	context['title'] = u'Удаление топика'
	Topic.objects.get(user=request.user, id=id).delete()
	return HttpResponse('ok')


@login_required
def moderated(request, id):
	context = {}
	topic = Topic.objects.get(id=id, moderated=False, public=True)
	form = ModeratedForm(request.POST or None, request.FILES or None)
	if form.is_valid():
		new_mod = form.save(commit=False)
		new_mod.topic = topic
		new_mod.user = request.user
		topic.moderated = True
		topic.public = False
		topic.save()
		new_mod.save()
		return redirect('subcategory', topic.subcategory.category.slug, topic.subcategory.slug )
	context['form'] = form
	return render(request, 'topic/moderated.html', context)


@login_required
def posts(request, id):
	context = {}
	topic = Topic.objects.get(id=id, moderated=False, public=True)
	context['posts'] = Post.objects.filter(topic=topic).order_by('-created_at')
	return render(request, 'topic/posts.html', context)


@login_required
def add_post(request, id):
	context = {}
	topic = Topic.objects.get(id=id, moderated=False, public=True)
	post_form = PostForm(request.POST or None)
	if post_form.is_valid():
		new_post = post_form.save(commit=False)
		new_post.user = request.user
		new_post.topic = topic
		new_post.save()
		topic = topic
		context['status'] = 'ok'
	else:
		context['status'] = 'Error'
	return HttpResponse(json.dumps(context), content_type='application/json')


@login_required
def edit_post(request, id):
	context = {}
	post = Post.objects.get(user=request.user, id=id)
	context['post_form'] = PostForm(request.POST or None, instance=post)
	if context['post_form'].is_valid():
		context['post_form'].save()
		return redirect('topic', post.topic.subcategory.slug, post.topic.id)
	context['post'] = post
	return render(request, 'topic/edit-post.html', context)


@login_required
def del_post(request, id):
	Post.objects.get(user=request.user, id=id).delete()
	return HttpResponse('ok')


@login_required
def good_vote(request, id):
	context = {}
	topic = Topic.objects.get(id=id, moderated=False, public=True)
	user_vote = Vote.objects.filter(user=request.user.id, topic=topic)
	if not user_vote:
		vote = Vote.objects.create(user=request.user, topic=topic)
		vote.good_vote = 0
		vote.good_vote += 1
		vote.save()
		context['status'] = 'ok'
	else:
		context['status'] = 'You have vote'
	return HttpResponse(json.dumps(context), content_type='application/json')


@login_required
def bad_vote(request, id):
	context = {}
	topic = Topic.objects.get(id=id, moderated=False, public=True)
	user_vote = Vote.objects.filter(user=request.user.id, topic=topic)
	if not user_vote:
		vote = Vote.objects.create(user=request.user, topic=topic)
		vote.bad_vote = 0
		vote.bad_vote += 1
		vote.save()
		context['status'] = 'ok'
	else:
		context['status'] = 'You have vote'
	return HttpResponse(json.dumps(context), content_type='application/json')


@login_required
def personal_message(request, id):
	context = {}
	context['title'] = u'Личное сообщение'
	context['topic'] = Topic.objects.get(id=id, moderated=False, public=True)
	context['personal_form'] = PersonalMessageForm(request.POST or None, request.FILES or None)
	if context['personal_form'].is_valid():
		personal_message = context['personal_form'].save(commit=False)
		personal_message.user = request.user
		personal_message.recipient = context['topic'].user
		personal_message.theme = context['topic'].title
		personal_message.topic = context['topic']
		personal_message.save()
	return render(request, 'topic/personal_message.html', context)


@login_required
def send_message(request, id):
	context = {}
	context['title'] = u'Личное сообщение'
	instance = TopicMessage.objects.get(id=id)
	context['personal_form'] = PersonalMessageForm(request.POST or None)
	if context['personal_form'].is_valid():
		personal_message = context['personal_form'].save(commit=False)
		personal_message.user = request.user
		personal_message.recipient = instance.user
		personal_message.parent = instance
		personal_message.theme = instance.theme
		personal_message.save()
	return render(request, 'topic/personal_message.html', context)


@login_required
def del_message(request, id):
	message = TopicMessage.objects.get(user=request.user, id=id)
	message.delete = True
	message.save()
	return HttpResponse('ok')


@login_required
def del_recipient_message(request, id):
	message = TopicMessage.objects.get(recipient=request.user, id=id)
	message.delete_recipient = True
	message.save()
	return HttpResponse('ok')


def tag(request, id):
	context = {}
	context['title'] = Tag.objects.get(id=id).word
	context['tag'] = Tag.objects.get(id=id)
	return render(request, 'blog/tag.html', context)

apps/blog/templates/topic/add-post.html
<form action="{% url 'add_post' topic.id %}" method="post" id="formx">
	{% csrf_token %}
	{{ post_form.errors }}
	<div>
		{% for field in post_form %}
			{{ field }}
		{% endfor %}
		<button type="submit" class="btn btn-default post_add_save_button" data-id="{{ topic.id }}"><i class="fa fa-commenting"></i> Оставить коментарий</button>
	</div>
</form>


<script>
	var vote_count = $('.post-count');

	$('.post_add_save_button').on('click', function(e){
		e.preventDefault();
		var msg = $('#formx').serialize();
		send_post_url = $('#formx').attr('action');
		topic_url = $('.post_add_save_button').data('id');
		$.ajax({
			type: 'POST',
			url: send_post_url,
			data: msg,
			success: function(response) {
				if (response.status == 'ok') {
					$( ".post_load" ).load("/posts/" + topic_url);
					var old_count = parseInt(vote_count.text(), 10);
					var new_count = old_count + 1;
					vote_count.text(new_count);
					$('#id_message').val(" ");
				}
			},
			error:  function(xhr, str){
					alert('Возникла ошибка: ' + xhr.responseCode);
			}
		});
	});
</script>

apps/blog/templates/topic/add-topic.html
{% extends 'base.html' %}
{% block content %}

	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			<h2 class="text-center">Создание топика</h2>
			<div class="panel panel-green margin-bottom-40">
				<div class="panel-body">
					<form action="" method="post" enctype="multipart/form-data" class="form-horizontal">
						{% csrf_token %}
						<div class="form-group">
							<label for="inputEmail1" class="col-lg-2 control-label">{{ form.title.label }}</label>
							<div class="col-lg-10">
								<input type="text" name="{{ form.title.name }}" class="form-control" value="{{ form.title.value|default_if_none:"" }}">
							</div>
						</div>

						<div class="form-group">
							<label for="inputEmail1" class="col-lg-2 control-label">{{ form.description.label }}</label>
							<div class="col-lg-10">
								<textarea cols="40" id="id_description" name="{{ form.description.name }}" class="form-control" rows="10">{{ form.description.value|default_if_none:"" }}</textarea>
							</div>
						</div>

						<div class="form-group">
							<label for="inputEmail1" class="col-lg-2 control-label">{{ form.tags.label }}</label>
							<div class="col-lg-10">
								{{ form.tags }}
							</div>
						</div>


						<div class="form-group">
							<div class="col-lg-offset-2 col-lg-10">
								<button type="submit" class="btn-add-topic">Создать</button>
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>

	<script>
		$('#id_tags').addClass('form-control')
		$(document).ready(function(){
			$('select').select2();
		});
	</script>

{% endblock %}

apps/blog/templates/topic/edit-post.html
<form action="{% url 'edit_post' post.id %}" method="post">
	{% csrf_token %}
	{{ post_form.errors }}
	<div>
		{% for field in post_form %}
			<label>{{ field.label }}</label>
			{{ field }}
		{% endfor %}
		<input type="submit" class="post_edit_save_button" data-token="{{ csrf_token }}">
	</div>
</form>

apps/blog/templates/topic/moderated.html
<form action="" method="post">
	{% csrf_token %}

	{{ form.errors }}
	{{ form }}
	<input type='submit'>
</form>

apps/blog/templates/topic/personal_message.html
{% extends 'base.html' %}
{% block content %}
	<form action="" method="post" enctype="multipart/form-data">
		{% csrf_token %}
		{{ personal_form.errors }}
		<div>
			{% for field in personal_form %}
				<label>{{ field.label }}</label>
				{{ field }}
			{% endfor %}
			<input type="submit">
		</div>
	</form>
{% endblock %}

apps/blog/templates/topic/posts.html
{% load thumbnail %}
{% load humanize %}

<script src="/static/blog/js/topic.js"></script>

{% for post in posts %}
	<div class="media" id='post_{{ post.id }}'>
		<a class="pull-left" href="#">
			{% if post.user.avatar %}
				{% thumbnail post.user.avatar "100x100" crop="center" as im %}
					<img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" class="media-object">
				{% endthumbnail %}
			{% else %}
				<img class="media-object" src="http://placehold.it/64x64" alt="">
			{% endif %}
		</a>
		<div class="media-body">
			<h4 class="media-heading">
				{% if post.user == user %}
					Вы
				{% else %}
					{{ post.user }}
				{% endif %}
				<small>{{ post.created_at|naturaltime }}</small>
				{% if user == post.user %}
					<small>
						<a href='{{ post.edit_post }}' class="post_edit_button" data-id='post_{{ post.id }}'>
							<i class="fa fa-pencil" aria-hidden="true"></i>
						</a>
						<a href="{{ post.delete_post }}" class="delete-post-button" data-id='post_{{ post.id }}'>
							<i class="fa fa-times" aria-hidden="true"></i>
						</a>
					</small>
				{% endif %}
			</h4>
			<div id='post_edit_{{ post.id }}' class='b-post__text'>{{ post.message }}</div>

			<a href='{{ post.edit_post }}' class='post_save_button'  data-id='post_{{ post.id }}' data-token='{{ csrf_token }}'>редактировать</a>

		</div>
	</div>
{% endfor %}


<script>

	$('.post_save_button').hide();

	$('.post_edit_button').on('click', function(e){
		e.preventDefault();
		edit_post_textarea = $('#' + $(this).data('id') + ' .b-post__text');
		edit_post_textarea.attr('contenteditable', 'true');
		edit_post_textarea.addClass('active-edit');
		edit_post_button = $('#' + $(this).data('id') + ' .post_save_button');
		edit_post_button.show();
	});

	$('.post_save_button').on('click', function(e){
		e.preventDefault();

		edit_post_url = $(this).attr('href');
		edit_post = $('#' + $(this).data('id'));
		edit_token = $(this).data('token');
		edit_post_textarea = $('#' + $(this).data('id') + ' .b-post__text');

		data = {
			'message': edit_post_textarea.text(),
			csrfmiddlewaretoken: edit_token
		}

		$.post(edit_post_url, data)
		.done(function(response){
			edit_post_textarea.attr('contenteditable', 'false');
			edit_post_textarea.removeClass('active-edit');
			$('.post_save_button').hide();
		})
	});

	$('.delete-post-button').on('click', function(e){
		e.preventDefault();
		delete_post_url = $(this).attr('href');
		delete_post_data = $('#' + $(this).data('id'));
		$.get(delete_post_url)
		.done(function(response) {
			delete_post_data.remove();
			var old_count = parseInt(vote_count.text(), 10);
			var new_count = old_count - 1;
			vote_count.text(new_count);
		})
	});

	$('.good_vote').on('click', function(e){
		e.preventDefault();

		$this = $(this);
		url = $this.attr('href');
		vote_count = $('.topic-good_vote__count');

		$.get(url)
		.done(function(response) {
			if (response.status == 'ok') {
				var old_count = parseInt(vote_count.text(), 10);
				var new_count = old_count + 1;
				vote_count.text(new_count);
			} else {
				$("#error-text").html('Вы уже проголосовали');
			}
		})
	})

	$('.bad_vote').on('click', function(e){
		e.preventDefault();

		$this = $(this);
		url = $this.attr('href');
		vote_count = $('.topic-bad_vote__count');

		$.get(url)
		.done(function(response) {
			if (response.status == 'ok') {
				var old_count = parseInt(vote_count.text(), 10);
				var new_count = old_count + 1;
				vote_count.text(new_count);
			} else {
				$("#error-text").html('Вы уже проголосовали');
			}
		})
	})
</script>

apps/blog/templates/topic/topic.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load humanize %}
{% block content %}
	<div class="row">
		<!-- Blog Post Content Column -->
		<div class="col-md-8 col-md-offset-2">
			<!-- Blog Post -->
			<!-- Title -->
			<div class="vote-div">
				{% if user.is_authenticated %}
					<a href="{{ topic.positive_vote }}" data-id='topic_{{ topic.id }}' class='good_vote'>
						<i class="fa fa-thumbs-o-up good-vote" aria-hidden="true"></i>
						<span class='topic-good_vote__count'>{{ topic.good_vote }}</span>
					</a>
					<a href="{{ topic.negative_vote }}" data-id='topic_{{ topic.id }}' class='bad_vote'>
						<i class="fa fa-thumbs-o-down bad-vote" aria-hidden="true"></i>
						<span class='topic-bad_vote__count'>{{ topic.bad_vote }}</span>
					</a>
				{% endif %}
				<p id='error-text'></p>
			</div>
			<h1>{{ topic.title }}</h1>
			{% if user.is_authenticated %}
				<a href="{% url 'moderated' topic.id %}" title="Жалоба модератору" class="topic-option">
					<i class="fa fa-lock" aria-hidden="true"></i>
				</a>
				<a href="{% url 'personal_message' topic.id %}" title="Написать топикпастеру" class="topic-option">
					<i class="fa fa-envelope-o" aria-hidden="true"></i>
				</a>
				<a href="" title="График" class="topic-option">
					<i class="fa fa-line-chart fa-3" aria-hidden="true"></i>
				</a>
			{% endif %}
			{% if user == topic.user %}
				<a href="{% url 'edit_topic' topic.id %}" title="Редактировать" class="topic-option">
					<i class="fa fa-pencil" aria-hidden="true"></i>
				</a>
				<a href="{% url 'del_topic' topic.id %}" title="Удалить" class="topic-option">
					<i class="fa fa-times" aria-hidden="true"></i>
				</a>
			{% endif %}</br>
			<i class="fa fa-tag" aria-hidden="true"></i>
			{% for tag in topic.tags.all %}
				<small>{{ tag.word }}*</small>
			{% endfor %}
			<hr>
			<!-- Date/Time -->
			<p><span class="glyphicon glyphicon-time"></span> Дата создания {{ topic.created_at|naturaltime }}</p>
			<hr>
			<!-- Post Content -->
			{{ topic.description }}
			<hr>
			<!-- Posted Comments -->
			<!-- Comment -->
			<h4 class="post_count">Комментарии (
				<span class="post-count">{{ topic.posts.count }}</span>

			)</h4>
			<div class="post_load">
				{% include 'topic/posts.html' %}
			</div>
			<hr>
			{% if user.is_authenticated %}
			<!-- Comments Form -->
				<h4>Написать комментарий:</h4>
				<div class="widget-area no-padding blank">
					<div class="status-upload">
						{% include 'topic/add-post.html' %}
					</div>
				</div>
			{% else %}
				<div class="alert alert-danger" role="alert">Только зарегистрированные пользователи могут оставлять комментарии. <a href="{% url 'login' %}">Войдите,</a> пожалуйста.</div>
			{% endif %}
		</div>
	</div>
{% endblock %}